# ASP.NET Core (.NET Framework)
# Build and test ASP.NET Core projects targeting the full .NET Framework.
# Add steps that publish symbols, save build artifacts, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/dotnet-core

trigger:
- master

pool:
  vmImage: 'windows-latest'

variables:
  solution: '**/*.sln'
  buildPlatform: 'Any CPU'
  buildConfiguration: 'Release'

steps:
- task: NodeTool@0
  inputs:
    versionSpec: '16.x'
    checkLatest: true
  displayName: 'Install Node.js'

- script: |
    npm install
  displayName: 'npm install'
  workingDirectory: '$(Build.SourcesDirectory)/UI/SysTicket.Client'

- script: |
    npm run build
  displayName: 'npm run build'
  workingDirectory: '$(Build.SourcesDirectory)/UI/SysTicket.Client'

- task: CopyFiles@2
  inputs:
    Contents: '$(Build.SourcesDirectory)/UI/SysTicket.Client/dist/**'
    TargetFolder: '$(Build.ArtifactStagingDirectory)'

- task: PublishBuildArtifacts@1
  inputs: 
    PathtoPublish: $(Build.ArtifactStagingDirectory)
    ArtifactName: 'www'